INVARIANT_STYLE = "VERISOL"
#INVARIANT_STYLE = "DAIKON"

RESULT_DIR = "./sok/result"
ENABLE_CACHE = True
CACHE_DIR = "./sok/cache"

# OPTION FOR ALL Falsified Invariants in the Output
ALLOW_FASIFY_INV = True

# OPTION FOR DISABLE IMPLICATION INVARIANTS
DISABLE_IMPLICATION_INV = True

# OPTION FOR Invariant Reduction with Dependency-based Pruning
ENABLE_INV_REDUCTION = False

# OPTION FOR Matching State Variables with Dynamic Storage Value Update
ENABLE_READ_MODEL_FLATTENVALUE = True

ETHERSCAN_API_KEY="SDI5QEC2UAY1CX4C1VPXC4WE9HIMH2SF1C"
QUICKNODE_API_KEY="661a68de75cca81104455a0cb1b244812d574fef"